apiVersion: pipeline.knative.dev/v1beta1
kind: PipelineRun
metadata:
  name: kritis-pipeline-run-12321312984
  namespace: default
spec:
    pipelineRef:
        name: kritis-pipeline
    pipelineParamsRef:
        name: pipelineparams-sample
    triggerRef:
        type: manual
status:
  taskRuns:
    - taskRef:
      name: unit-test-kritis-12321312984
      nextTasks:
        - taskRef:
            name: push-kritis-12321312984
      prevTasks: []
    - taskRef:
      name: push-kritis-12321312984
      nextTasks: []
      prevTasks:
        - taskRef:
          name: unit-test-kritis-12321312984
  conditions:
    - type: Valid
      status: "True"
      lastTransitionTime: "2018-10-04T12:25:39Z"
      reason: created
      message: "PipelineRun has been validated"
    - type: Started
      status: "True"
      lastTransitionTime: "2018-10-04T12:25:39Z"
      reason: manualTrigger
      message: "Pipeline has been triggered manually"
    - type: Completed
      status: "True"
      lastTransitionTime: "2018-10-04T13:25:39Z"
      reason: done
      message: "Pipeline execution has finished"
    - type: Successful
      status: "False"
      lastTransitionTime: "2018-10-04T13:25:39Z"
      reason: taskFailure
      message: "TaskRun `build-push-kritis-12321312984` had non-zero exit code"
