apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: kritis-pipeline-run-12321312984
  namespace: default
spec:
    pipelineRef:
        name: kritis-pipeline
    pipelineParamsRef:
        name: pipelineparams-sample
    triggerRef:
        type: manual
status:
  taskRuns:
    - taskRef: unit-test-kritis-12321312984
    - taskRef: push-kritis-12321312984
  conditions:
    - type: Succeeded
      status: "False"
      lastTransitionTime: "2018-10-04T12:25:39Z"
      reason: taskFailure
      message: "TaskRun `build-push-kritis-12321312984` had non-zero exit code"
