run:
  build-tags:
  - e2e
  skip-dirs:
  - vendor
  - pkg/client/(.*)/fake
  - pkg/client/resource/(.*)/fake
  timeout: 5m
linters-settings:
  errcheck:
    exclude: .errcheck.txt
linters:
  enable:
  - errcheck
  - gofmt
  - goimports
  - gosec
  - gocritic
  - golint
