# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "github.com/knative/caching/pkg/apis/caching",
  "github.com/knative/test-infra/scripts",
]

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[override]]
  name = "github.com/json-iterator/go"
  # This is the commit at which k8s depends on this in 1.11
  # It seems to be broken at HEAD.
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "github.com/Azure/go-autorest"
  # This is the commit at which k8s depends on this in 1.11
  # It seems to be broken at HEAD.
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]]
  name = "github.com/knative/pkg"
  # HEAD as of 2018-10-30
  revision = "02b354e3a4fc52a1df245b4069671f082ce321d1"

[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"

[[constraint]]
  name = "github.com/knative/build"
  # HEAD as of 2018-11-9
  revision = "db94a44721837a973c20a95b3dec9af360783656"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/knative/caching"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/knative/test-infra"
  non-go = false
