apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: taskruns.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: TaskRun
    plural: taskruns
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            inputs:
              properties:
                params:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - value
                    type: object
                  type: array
                resourcesVersion:
                  items:
                    properties:
                      resourceRef:
                        properties:
                          apiVersion:
                            type: string
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      version:
                        type: string
                    required:
                    - resourceRef
                    - version
                    type: object
                  type: array
              required:
              - resourcesVersion
              type: object
            outputs:
              properties:
                resources:
                  items:
                    properties:
                      name:
                        type: string
                      resourceRef:
                        properties:
                          apiVersion:
                            type: string
                          name:
                            type: string
                        required:
                        - name
                        type: object
                    required:
                    - name
                    - resourceRef
                    type: object
                  type: array
                results:
                  items:
                    properties:
                      format:
                        type: string
                      name:
                        type: string
                      path:
                        type: string
                    required:
                    - name
                    - format
                    - path
                    type: object
                  type: array
              type: object
            results:
              properties:
                logs:
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    url:
                      type: string
                  required:
                  - name
                  - type
                  - url
                  type: object
                runs:
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    url:
                      type: string
                  required:
                  - name
                  - type
                  - url
                  type: object
                tests:
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    url:
                      type: string
                  required:
                  - name
                  - type
                  - url
                  type: object
              required:
              - runs
              - logs
              type: object
            taskRef:
              properties:
                apiVersion:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
            trigger:
              properties:
                triggerRef:
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  type: object
              required:
              - triggerRef
              type: object
          required:
          - taskRef
          - trigger
          - results
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - lastTransitionTime
                type: object
              type: array
            steps:
              items:
                properties:
                  exitCode:
                    format: int64
                    type: integer
                  logsURL:
                    type: string
                  name:
                    type: string
                required:
                - name
                - logsURL
                - exitCode
                type: object
              type: array
          required:
          - steps
          - conditions
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
