apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelineruns.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: PipelineRun
    plural: pipelineruns
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            pipelineParamsRef:
              properties:
                apiVersion:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
            pipelineRef:
              properties:
                apiVersion:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
            triggerRef:
              properties:
                name:
                  type: string
                type:
                  type: string
              required:
              - type
              type: object
          required:
          - pipelineRef
          - pipelineParamsRef
          - triggerRef
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - lastTransitionTime
                type: object
              type: array
            resourceVersion:
              items:
                properties:
                  resourceRef:
                    properties:
                      apiVersion:
                        type: string
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  version:
                    type: string
                required:
                - resourceRef
                - version
                type: object
              type: array
            taskRuns:
              items:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - conditions
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
