apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelines.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: Pipeline
    plural: pipelines
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            resources:
              items:
                properties:
                  name:
                    type: string
                  resourceRef:
                    properties:
                      apiVersion:
                        type: string
                      name:
                        type: string
                    required:
                    - name
                    type: object
                required:
                - name
                - resourceRef
                type: object
              type: array
            tasks:
              items:
                properties:
                  clusterBindings:
                    items:
                      properties:
                        inputName:
                          type: string
                        key:
                          type: string
                      required:
                      - key
                      - inputName
                      type: object
                    type: array
                  inputSourceBindings:
                    items:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                        passedConstraints:
                          items:
                            type: string
                          type: array
                      required:
                      - name
                      - key
                      type: object
                    type: array
                  name:
                    type: string
                  outputSourceBindings:
                    items:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                        passedConstraints:
                          items:
                            type: string
                          type: array
                      required:
                      - name
                      - key
                      type: object
                    type: array
                  params:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  taskRef:
                    properties:
                      apiVersion:
                        type: string
                      name:
                        type: string
                    required:
                    - name
                    type: object
                required:
                - name
                - taskRef
                type: object
              type: array
          required:
          - tasks
          - resources
          type: object
        status:
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
