apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelineparams.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: PipelineParams
    plural: pipelineparams
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusters:
              items:
                properties:
                  endpoint:
                    type: string
                  name:
                    type: string
                  type:
                    type: string
                required:
                - name
                - type
                - endpoint
                type: object
              type: array
            results:
              properties:
                logs:
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    url:
                      type: string
                  required:
                  - name
                  - type
                  - url
                  type: object
                runs:
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    url:
                      type: string
                  required:
                  - name
                  - type
                  - url
                  type: object
                tests:
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    url:
                      type: string
                  required:
                  - name
                  - type
                  - url
                  type: object
              required:
              - runs
              - logs
              type: object
            serviceAccount:
              type: string
          required:
          - serviceAccount
          - results
          type: object
        status:
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
