apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: tasks.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: Task
    plural: tasks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            buildSpec:
              properties:
                steps:
                  items:
                    type: object
                  type: array
                template:
                  properties:
                    arguments:
                      items:
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                        required:
                        - name
                        - value
                        type: object
                      type: array
                    env:
                      items:
                        type: object
                      type: array
                    name:
                      type: string
                  required:
                  - name
                  type: object
              type: object
            inputs:
              properties:
                params:
                  items:
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                    required:
                    - name
                    - type
                    type: object
                  type: array
                sources:
                  items:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  type: array
              type: object
            outputs:
              properties:
                artifacts:
                  items:
                    properties:
                      name:
                        type: string
                      storeKey:
                        type: string
                      type:
                        type: string
                    required:
                    - name
                    - type
                    - storeKey
                    type: object
                  type: array
                results:
                  items:
                    properties:
                      format:
                        type: string
                      name:
                        type: string
                      path:
                        type: string
                    required:
                    - name
                    - format
                    - path
                    type: object
                  type: array
              type: object
          required:
          - buildSpec
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - lastTransitionTime
                type: object
              type: array
          required:
          - conditions
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
