apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: microservices-pipeline-run
  namespace: default
spec:
  pipelineRef:
    name: microservices-pipeline
  resources:
    - name: build-productcatalog
      inputs:
        - name: workspace
          resourceRef:
            name: hipster-git-source
      outputs:
        - name: builtImage
          resourceRef:
            name: productcatalogservice-image
    - name: build-checkoutservice
      inputs:
        - name: workspace
          resourceRef:
            name: hipster-git-source
      outputs:
        - name: builtImage
          resourceRef:
            name: checkoutservice-image
    - name: build-frontend
      inputs:
        - name: workspace
          resourceRef:
            name: hipster-git-source
      outputs:
        - name: builtImage
          resourceRef:
            name: frontend-image
    - name: deploy-all
      inputs:
        - name: workspace
          resourceRef:
            name: hipster-git-source
          providedBy:
            - build-checkoutservice
            - build-productcatalog
            - build-frontend