apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: home-is-set-
spec:
  taskSpec:
    steps:
    - image: busybox
      script: |
        #!/usr/bin/env sh
        [[ $HOME == /tekton/home ]]
