kind: Secret
apiVersion: v1
metadata:
  name: secret-vol-password
stringData:
  ninja: SECRET_PASSWORD
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: secret-volume
spec:
  taskSpec:
    steps:
    - image: busybox
      script: |
        #!/usr/bin/env sh
        SECRET_PASSWORD=$(cat /var/secret/ninja)
        [[ $SECRET_PASSWORD == SECRET_PASSWORD ]]
      volumeMounts:
      - name: secret-volume
        mountPath: /var/secret
    volumes:
    - name: secret-volume
      secret:
        secretName: secret-vol-password
