apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: sidecar-interp-
spec:
  taskSpec:
    inputs:
      params:
        - name: some-input
          default: foo
    volumes:
      - name: shared
        emptyDir: {}
    sidecars:
      - name: value-sidecar
        image: busybox
        command:
          - /bin/sh
        args:
          - -c
          - "echo $(inputs.params.some-input) > /shared/value && sleep infinity"
        volumeMounts:
          - name: shared
            mountPath: /shared
    steps:
      - name: check-value
        image: busybox
        script: |
          #!/bin/sh
          VALUE=$(cat /shared/value)
          [[ $VALUE == 'foo' ]]
        volumeMounts:
          - name: shared
            mountPath: /shared
