apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: custom-volume-
spec:
  taskSpec:
    steps:
    - name: write
      image: busybox
      script: |
        #!/usr/bin/env sh
        echo some stuff > /im/a/custom/mount/path/file
      volumeMounts:
      - name: custom
        mountPath: /im/a/custom/mount/path
    - name: read
      image: busybox
      script: |
        #!/usr/bin/env sh
        cat /short/and/stout/file | grep stuff
      volumeMounts:
      - name: custom
        mountPath: /short/and/stout
    volumes:
    - name: custom
      emptyDir: {}
