apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: steptemplate-env-merge-
spec:
  params:
  - name: FOO
    value: foo
  - name: BAR
    value: bar
  taskSpec:
    # This template will be applied to all steps
    stepTemplate:
      env:
      - name: QUX
        value: original
    params:
    - name: FOO
      description: FOO variable
    - name: BAR
      description: BAR variable
    - name: FOOBAR
      description: FOOBAR variable
      default: foobar
    steps:
      # Test the environment variables are set in the task
      - name: foo
        image: busybox
        script: |
          #!/usr/bin/env sh
          [[ $FOO == "foo" ]]
        env:
        - name: FOO
          value: $(params.FOO)
      - name: foobar
        image: busybox
        script: |
          #!/usr/bin/env sh
          [[ $FOOBAR == "foobar" ]]
        env:
        - name: FOOBAR
          value: $(params.FOOBAR)
      - name: bar
        image: busybox
        script: |
          #!/usr/bin/env sh
          [[ $BAR == "bar" ]]
        env:
        - name: BAR
          value: $(params.BAR)
      # Use the env var from the stepTemplate
      - name: qux-no-override
        image: busybox
        script: |
          #!/usr/bin/env sh
          [[ $QUX == "original" ]]
      # Override the env var in the stepTemplate
      - name: qux-override
        image: busybox
        script: |
          #!/usr/bin/env sh
          [[ $QUX == "override" ]]
        env:
        - name: QUX
          value: override
