kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-taskrun-
spec:
  taskSpec:
    steps:
    - image: busybox
      name: print-uid
      script: |
        echo "TaskRunUID name: $(context.taskRun.uid)"
    - image: busybox
      name: print-names
      script: |
        echo "Task name: $(context.task.name)"
        echo "TaskRun name: $(context.taskRun.name)"
