apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: workingdir-
spec:
  taskSpec:
    steps:
    - name: default
      image: busybox
      script: |
        #!/usr/bin/env sh
        [[ $PWD == /workspace ]]

    - name: override
      image: busybox
      workingDir: '/a/path/too/far'
      script: |
        #!/usr/bin/env sh
        [[ $PWD == /a/path/too/far ]]
