apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: workspace-volume-
spec:
  taskSpec:
    steps:
    - name: write
      image: busybox
      script: echo some stuff > /workspace/stuff
    - name: read
      image: busybox
      script: cat /workspace/stuff

    - name: override-workspace
      image: busybox
      # /workspace/stuff *doesn't* exist.
      script: |
        #!/usr/bin/env sh
        [[ ! -f /workspace/stuff ]]
      volumeMounts:
      - name: empty
        mountPath: /workspace

    volumes:
    - name: empty
      emptyDir: {}
