apiVersion: pipeline.knative.dev/v1beta1
kind: PipelineParams
metadata:
  name: wizzbang-pipeline-params
  namespace: default
spec:
    serviceAccount: 'wizzbangPipelineServiceAccount'
    sources:
        - name: 'wizzbang'
          type: 'github'
          url: 'github.com/wizzbangcorp/wizzbang'
          branch: 'master'
          commit: 'HEAD'
    artifactStores:
        - name: 'prodRegistry'
          type: 'imageRegistry'
          url: 'gcr.io/wizzbang'
        - name: 'stagingRegistry'
          type: 'imageRegistry'
          url: 'gcr.io/wizzbang-staging'
    results:
        runs:
          name: 'runsBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/runs'
          token: 'todo'
        logs:
          name: 'logBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/logs'
          token: 'todo'
        tests:
          name: 'testBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/tests'
          token: 'todo'
    clusters:
        - name: 'prod'
          type: 'gke'
          endpoint: 'https://prod.gke.corp.com'
status:
    conditions:
        - type: Valid
          status: "True"
          lastTransitionTime: "2018-10-04T12:25:39Z"
          reason: created
          message: "PipelineParams have been validated"