apiVersion: pipeline.knative.dev/v1beta1
kind: Resource
metadata:
  name: wizzbang-resources
  namespace: default
spec:
  resources:
  - name: wizzbang
    type: git
    params:
    - name: url
      value: github.com/wizzbangcorp/wizzbang
    - name: revision
      value: HEAD
  - name: wizzbangStagingImage
    type: image
    params:
    - name: url
      value: gcr.io/wizzbang-staging