apiVersion: pipeline.knative.dev/v1beta1
kind: Pipeline
metadata:
  name: wizzbang-pipeline
  namespace: default
spec:
    tasks:
      - name: 'test'
        taskRef:
          name: test-wizzbang-task
        inputsourceBindings:
          - name: repoUnderTest
            key: wizzbang
      - name: 'buildPush'
        taskRef:
          name: build-push-task
        inputSourceBindings:
          - name: 'workspace'
            key: 'wizzbang'
            passedConstraint: [test-wizzbang-task]
        outputSourceBindings:
          - name: registry
            key: wizzbangStagingImage
        params:
          - name: pathToDockerfile
            value: build/Dockerfile
      - name: integrationTest
        taskRef:
          name: integration-test-wizzbang-task
        inputSourceBindings:
          - name: repoUnderTest
            key: wizzbang
            passedConstraint: [test]
        outputSourceBindings:
          - name: registry
            key: wizzbangStagingImage
            passedConstraint: [build-push-task]
      - name: deploy
        taskRef:
            name: deploy-with-helm
        params:
          - name: pathToHelmCharts
            value: deploy/helm
        inputSourceBindings:
          - name: repoToDeploy
            key: wizzbang
            passedConstraint: [integration-test-wizzbang-task]
        clusterBindings:
          - clusterName: prod
        outputSourceBindings:
          - name: registry
            key: wizzbangStagingImage
            passedConstraint: [build-push-task]
    resources:
    - name: wizzbang
      resourceRef:
        name: wizzbang
    - name: wizzbangStagingImage
      resourceRef:
        name: wizzbangStagingImage   