apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: build-push-task
  namespace: default
spec:
    inputs:
        resources:
           - resourceRef:
               name: resource-name
             name: workspace
        params:
           - name: PATH_TO_DOCKERFILE
             value: string
    outputs:
        resources:
         - resourceRef:
             name: registry
           name: builtImage # registy is the name of the ArtifactStore
    buildSpec:
        template:
            name: kaniko
            arguments:
                - name: DOCKERFILE
                  value: ${PATH_TO_DOCKERFILE}
                - name: REGISTRY
                  value: ${REGISTRY}