apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: create-file
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
      targetPath: /damnworkspace
  steps:
  - name: read-docs-old
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'ls -la /workspace/damnworkspace/docs/install.md']
  - name: write-new-stuff
    image: ubuntu
    command: ['bash']
    args: ['-c', 'echo some stuff > /workspace/damnworkspace/stuff']

---
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: check-stuff-file-exists
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
      targetPath: /newworkspace
  steps:
  - name: lsread
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'ls -la /workspace/newworkspace/']
  - name: read
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'cat /workspace/newworkspace/stuff']

---
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kritis-resources-git
  namespace: default
spec:
  type: git
  params:
  - name: url
    value: https://github.com/grafeas/kritis
  - name: revision
    value: master