apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: build-push-task
  namespace: default
spec:
    inputs:
        resources:
           - name: workspace
             type: git
        params:
           - name: PATH_TO_DOCKERFILE
             value: string
    outputs:
        resources:
          - name: builtImage 
    buildSpec:
        template:
            name: kaniko
            arguments:
                - name: DOCKERFILE
                  value: ${PATH_TO_DOCKERFILE}
                - name: REGISTRY
                  value: ${REGISTRY}