apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineParams
metadata:
  name: wizzbang-pipeline-params
  namespace: default
spec:
    serviceAccount: 'wizzbangPipelineServiceAccount'
    results:
        runs:
          name: 'runsBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/runs'
          token: 'todo'
        logs:
          name: 'logBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/logs'
          token: 'todo'
        tests:
          name: 'testBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/tests'
          token: 'todo'
    clusters:
        - name: 'prod'
          type: 'gke'
          endpoint: 'https://prod.gke.corp.com'