apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: wizzbang-pipeline-run-sd8f8dfasdfasdfas
  namespace: default
spec:
    pipelineRef:
        name: wizzbang-pipeline
    pipelineParamsRef:
        name: wizzbang-pipeline-params
    triggerRef:
        type: manual
status:
  taskRuns:
    - taskRef:
      name: test-wizzbang-task-run-sd8f8dfasdfasdfas
    - taskRef:
      name: build-push-task-run-sd8f8dfasdfasdfas
  conditions:
    - type: Started
      status: "True"
      lastTransitionTime: "2018-10-04T12:25:39Z"
      reason: manualTrigger
      message: "Pipeline has been triggered manually"
    - type: Completed
      status: "True"
      lastTransitionTime: "2018-10-04T13:25:39Z"
      reason: done
      message: "Pipeline execution has finished"
    - type: Successful
      status: "False"
      lastTransitionTime: "2018-10-04T13:25:39Z"
      reason: taskFailure
      message: "TaskRun `test-wizzbang-build-push-run-sd8f8dfasdfasdfas` had non-zero exit code"