apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: wizzbang-pipeline
  namespace: default
spec:
    tasks:
      - name: test
        taskRef:
          name: test-wizzbang-task
        inputsourceBindings:
          - name: repoUnderTest
            key: workspace
            resourceRef:
              name: wizzbang-git
      - name: buildPush
        taskRef:
          name: build-push-task
        inputSourceBindings:
          - name: wizzbangSrc
            key: workspace
            resourceRef:
              name: wizzbang-git
            passedConstraint: [test-wizzbang-task]
        outputSourceBindings:
          - name: wizzbangImage
            key: builtImage
            resourceRef:
              name: wizzbang-image
        params:
          - name: pathToDockerfile
            value: build/Dockerfile
      - name: integrationTest
        taskRef:
          name: integration-test-wizzbang-task
        inputSourceBindings:
          - name: repoUnderTest
            key: wizzbang
            resourceRef:
              name: wizzbang-git
            passedConstraint: [test]
        outputSourceBindings:
          - name: wizzbangImage
            key: builtImage
            resourceRef:
              name: wizzbang-image
            passedConstraint: [build-push-task]
      - name: deploy
        taskRef:
            name: deploy-with-helm
        params:
          - name: pathToHelmCharts
            value: deploy/helm
        inputSourceBindings:
          - name: wizzbangSrc
            key: wizzbang
            resourceRef:
              name: wizzbang-git
            passedConstraint: [integration-test-wizzbang-task]
        clusterBindings:
          - inputName: prod
            key: prod
        outputSourceBindings:
          - name: wizzbangImage
            key: builtImage
            resourceRef:
              name: wizzbang-image
            passedConstraint: [build-push-task] 