apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelineruns.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: PipelineRun
    plural: pipelineruns
    categories:
    - all
    - knative
    - build-pipeline    
  scope: Namespaced
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
