apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: build-push
  namespace: default
spec:
    inputs:
        resources:
        - resourceRef:
            name: resource-name
          name: workspace
        params:
            - name: pathToDockerFile
              value: string
    outputs:
        resources:
        - resourceRef:
            name: registry
          name: builtImage
    buildSpec:
        template:
            name: kaniko
            arguments:
                - name: DOCKERFILE
                  value: ${pathToDockerFile}
                - name: REGISTRY
                  value: ${registry}
