apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-helm
  namespace: default
spec:
    inputs:
        resources:
            - resourceRef:
                name: resource-name
              name: workspace
        params:
            - name: pathToHelmCharts
              value: string
            - name: helmArgs
              value: string
            - name: image
              value: string
        cluster:
            - name: clusterName
    buildSpec:
        steps:
        - name: deploy
          image: kubernetes-helm
          args: ['deploy', '--path=${pathToHelmChart}', '--set image=${image}', '${helmArgs}']

---
apiVersion: pipeline.knative.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
  namespace: default
spec:
    inputs:
        resources:
          - resourceRef:
              name: resource-name
            name: workspace
        params:
            - name: kubectlArgs
              value: string
            - name: pathToFiles
              value: string
        cluster:
            - name: targetCluster
    buildSpec:
        steps:
        - name: runKubectl
          image: k8s-kubectl
          args: ['--use-context', '${targetCluster}', '--namespace', '${targetCluster.namespace}', 'apply', '-c', '${pathToFiles}', '${kubectlArgs}']
