apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: output-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: first-create-file          # 1. create file
    taskRef:
      name: create-file
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: workspace
        resource: source-repo
  - name: then-check                 # 2.  check file exists
    taskRef:
      name: check-stuff-file-exists
    resources:
      inputs:
      - name: workspace
        resource: source-repo
        from: [first-create-file]
