apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: make
  namespace: default
spec:
    inputs:
        resources:
          - name: workspace
            type: git
        params:
          - name: makeTarget
    outputs:
        results:
            - name: testResults
              format: junit
              path: logs/tests.xml
    buildSpec:
        steps:
            - name: runMake
              image: ubuntu
              args: ['make', '${makeTarget}']

---
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: integration-test-in-docker
  namespace: default
spec:
    inputs:
        resources:
           - name: workspace
             type: git
        params:
            - name: testImage
            - name: testArgs
    outputs:
        results:
            - name: testResults
              format: junit
              path: integration/logs/tests.xml
    buildSpec:
        steps:
            - name: runTests
              image: '${testImage}'
              args: ['${testArgs}']
              volumeMounts:
              - name: gac
                mountPath: gac.json
              - name: cloudconfig
                mountPath: /root/.config/gcloud
              - name: dockerSocket
                mountPath: /var/run/docker.sock
        volumes:
            - name: gac
              hostPath:
                path: ${workspace}/config/gac.json
            - name: cloudconfig
              hostPath:
                path: ${workspace}/config/gcloud
            - name: dockerSocket
              hostPath:
                path: /var/run/docker.sock

