apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: guestbook-resources-git
  namespace: default
spec:
  type: git
  params:
  - name: url
    value: github.com/kubernetes/examples
  - name: revision
    value: HEAD      
---      
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: guestbook-resources-redis-docker
  namespace: default
spec:
  type: git
  params:
  - name: url
    value: github.com/GoogleCloudPlatform/redis-docker/
  - name: revision
    value: HEAD
---        
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: guestbookstagingimage
  namespace: default
spec:        
  type: image
  params:
  - name: url
    value: gcr.io/demo-staging
---        
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: redisstagingimage
  namespace: default
spec:        
  type: image
  params:
  - name: url
    value: gcr.io/redis-demo-staging
---    
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: testcluster
  namespace: default
spec:  
  type: cluster
  params:
  - name: url
    value: https://prod.gke.corp.com  
  - name: cadata
    value: LS0tLS1......  # cert for your cluster
  - name: token
    value: eyJhbGciOiJ.....  # token for the username specified 
  - name: username
    value: admin