apiVersion: pipeline.knative.dev/v1alpha1
kind: Resource
metadata:
  name: guestbook-resources-git
  namespace: default
spec:
    type: git
    params:
    - name: url
      value: github.com/kubernetes/examples
    - name: revision
      value: HEAD      
    - name: serviceAccount
      value: githubServiceAccount
---      
apiVersion: pipeline.knative.dev/v1alpha1
kind: Resource
metadata:
  name: guestbook-resources-redis-docker
  namespace: default
spec:
    type: git
    params:
      - name: url
        value: github.com/GoogleCloudPlatform/redis-docker/
      - name: serviceAccount
        value: githubServiceAccount
      - name: revision
        value: HEAD
---        
apiVersion: pipeline.knative.dev/v1alpha1
kind: Resource
metadata:
  name: guestbookstagingimage
  namespace: default
spec:        
    type: image
    params:
      - name: url
        value: gcr.io/demo-staging
---        
apiVersion: pipeline.knative.dev/v1alpha1
kind: Resource
metadata:
  name: redisstagingimage
  namespace: default
spec:        
    type: image
    params:
      - name: url
        value: gcr.io/redis-demo-staging       