apiVersion: pipeline.knative.dev/v1beta1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
    tasks:
      - name: unit-test-kritis          # 1.  Run unit Tests
        taskRef:
          name: make
        inputSourceBindings:
          - name: workspace
            key: kritis-app-github
        params:
          - name: makeTarget
            value: test
      - name: push-kritis               # 2.  Build And Push Tests
        taskRef:
          name: build-push
        inputSourceBindings:
          - name: workspace
            key: kritis-app-github
            passedConstraint: 
              - make
        outputSourceBindings:
          - name: registry
            key: stagingRegistry
        params:
          - name: pathToDockerfile
            value: deploy/Dockerfile
      - name: deploy-test-env           # 3. Finally Deploy to Test environment
        taskRef:
          name: deploy-with-helm
        inputSourceBindings:
          - name: registry
            key: stagingRegistry
            passedConstraint: [build-push]
        params:
          - name: pathToHelmCharts
            value: kritis-charts
        clusterBindings:
          - clusterName: test
      - name: integration-test          # 4. Run Integration Tests in test cluster
        taskRef:
          name: integration-test-in-docker
        inputSourceBindings:
          - name: workspace
            key: kritis-test-github
            passedConstraint: [deploy-with-helm]
        params:
          - name: testArgs
            value: "-e REMOTE_INTEGRATION=true"
    resources:
      - name: kritis-app-github
        resourceRef:
          name: kritis-app-github-resource
      - name: kritis-test-github
        resourceRef:
          name: kritis-test-github-resource
      - name: stagingRegistry
        resourceRef:
          name: stagingRegistry-resource                    
