apiVersion: pipeline.knative.dev/v1beta1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
    tasks:
      - name: unit-test-kritis          # 1.  Run unit Tests
        taskRef:
          name: make
        inputSourceBindings:
          - name: workspace
            sourceKey: kritis-app-github
        params:
          - name: makeTarget
            type: test
      - name: push-kritis               # 2.  Build And Push Tests
        taskRef:
          name: build-push
        inputSourceBindings:
          - name: workspace
            sourceKey: kritis-app-github
            passedConstraint: 
              - make
        outputSourceBindings:
          - name: registry
            sourceKey: stagingRegistry
        params:
          - name: pathToDockerfile
            type: deploy/Dockerfile
      - name: deploy-test-env           # 3. Finally Deploy to Test environment
        taskRef:
          name: deploy-with-helm
        inputSourceBindings:
          - name: registry
            sourceKey: stagingRegistry
            passedConstraint: [build-push]
        params:
          - name: pathToHelmCharts
            type: kritis-charts
        clusterBindings:
          - clusterName: test
      - name: integration-test          # 4. Run Integration Tests in test cluster
        taskRef:
          name: integration-test-in-docker
        inputSourceBindings:
          - name: workspace
            sourceKey: kritis-test-github
            passedConstraint: [deploy-with-helm]
        params:
          - name: testArgs
            type: "-e REMOTE_INTEGRATION=true"
    resources:
      - name: kritis-app-github
        resourceRef:
          name: kritis-app-github
        type: git
        url: https://github.com/grafeas/kritis
        revision: master
      - name: kritis-test-github
        resourceRef:
          name: kritis-test-github
        type: git
        url: https://github.com/grafeas/kritis-test
        revision: master
      - name: stagingRegistry
        resourceRef:
          name: stagingRegistry
        type: image
        digest: latest
                      
