apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
    tasks:
      - name: unit-test-kritis          # 1.  Run unit Tests
        taskRef:
          name: make
        inputSourceBindings:
          - name: kritis-app-github
            key: workspace # bind to the name in the task
            resourceRef:
              name: kritis-resources-git
        params:
          - name: makeTarget
            value: test
      - name: push-kritis               # 2.  Build And Push Tests
        taskRef:
          name: build-push
        inputSourceBindings:
          - name: kritis-app-github
            key: workspace # bind to the name in the task
            resourceRef:
              name: kritis-resources-git
            passedConstraints: [unit-test-kritis]
        outputSourceBindings:
          - name: kritisImage
            key: builtImage # bind to the name in the task
            resourceRef:
              name: kritis-resources-image
        params:
          - name: pathToDockerfile
            value: deploy/Dockerfile
      - name: deploy-test-env           # 3. Finally Deploy to Test environment
        taskRef:
          name: deploy-with-helm
        inputSourceBindings:
          - name: guestbookImage
            key: workspace
            resourceRef:
              name: kritis-resources-image
            passedConstraints: [push-kritis]
        params:
          - name: pathToHelmCharts
            value: kritis-charts
        clusterBindings:
          - inputName: targetCluster
            key: testCluster
      - name: integration-test          # 4. Run Integration Tests in test cluster
        taskRef:
          name: integration-test-in-docker
        inputSourceBindings:
          - name: kritis-test-github
            key: workspace
            resourceRef:
                name: kritis-resources-test-git
            passedConstraints: [deploy-test-env]
        params:
          - name: testArgs
            value: "-e REMOTE_INTEGRATION=true"
