apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
  tasks:
  - name: unit-test-kritis          # 1.  Run unit Tests
    taskRef:
      name: make
    inputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
    params:
    - name: makeTarget
      value: test
  - name: push-kritis               # 2.  Build And Push Tests
    taskRef:
      name: build-push
    inputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
      providedBy: [unit-test-kritis]
    outputSourceBindings:
    - name: builtImage
      resourceRef:
        name: kritis-resources-image
    params:
    - name: pathToDockerfile
      value: deploy/Dockerfile
  - name: deploy-test-env           # 3. Finally Deploy to Test environment
    taskRef:
      name: deploy-with-helm
    inputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
    - name: builtImage
      resourceRef:
        name: kritis-resources-image
      providedBy: [push-kritis]
    - name: testCluster
      resourceRef:
        name: kritistestcluster  
    params:
    - name: pathToHelmCharts
      value: kritis-charts
  - name: integration-test          # 4. Run Integration Tests in test cluster
    taskRef:
      name: integration-test-in-docker
    inputSourceBindings:
    - name: workspace
      resourceRef:
          name: kritis-resources-git
      providedBy: [deploy-test-env]
    params:
    - name: testArgs
      value: "-e REMOTE_INTEGRATION=true"
    - name: testCommand
      value: "make integration-in-docker"