apiVersion: pipeline.knative.dev/v1beta1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
    tasks:
        - name: unit-test-kritis          # 1.  Run unit Tests
          taskRef:
              name: make
          inputSourceBindings:
              - inputName: workspace
                sourceKey: kritis
          params:
              - name: makeTarget
                value: test
        - name: push-kritis               # 2.  Build And Push Tests
          taskRef:
              name: build-push
          inputSourceBindings:
              - name: workspace
                sourceKey: kritis
          outputSourceBindings:
              - name: registry
                sourceKey: stagingRegistry
          params:
              - name: pathToDockerfile
                value: deploy/Dockerfile
          prevTasks: ['unit-test-kritis']
        - name: deploy-test-env           # 3. Finally Deploy to Test environment
          taskRef:
              name: deploy-with-helm
          inputSourceBindings:
              - name: workspace
                sourceKey: kritis
              - name: registry
                sourceKey: stagingRegistry
                passedConstraints: [push-kritis]
          params:
              - name: pathToHelmCharts
                value: kritis-charts
          clusterBindings:
              - clusterName: test
          nextTasks: ['integration-test']
        - name: integration-test          # 4. Run Integration Tests in test cluster
          taskRef:
              name: integration-test-in-docker
          inputSourceBindings:
              - name: workspace
                sourceKey: kritis
          params:
              - name: testArgs
                value: "-e REMOTE_INTEGRATION=true"
    sources:
      - name: kritis
        type: git
        params:
          - name: url
            value: https://github.com/grafeas/kritis
          - name: branch
            value: master
      - name: stagingRegistry
        type: image
        params:
          - name: buildImage
            value: kritis       
  
                      
