apiVersion: tekton.dev/v1alpha2
kind: TaskRun
metadata:
  generateName: home-is-set-
spec:
  taskSpec:
    steps:
    - image: ubuntu
      script: |
        #!/usr/bin/env bash
        [[ $HOME == /tekton/home ]]
