apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: kritis-pipeline-2
  namespace: default
spec:
  tasks:
  - name: create-file-kritis-1          # 1. create file
    taskRef:
      name: create-file
    inputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
    outputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git  # altered git resource
  - name: create-another-file-kritis          # 1. create file
    taskRef:
      name: create-file-stuff2
    inputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
    outputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git 
  - name: check-kritis               # 2.  check file exists
    taskRef:
      name: check-files-exists
    inputSourceBindings:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
      providedBy:
      - create-file-kritis-1
      - create-another-file-kritis