apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: output-pipeline-run
spec:
  pipelineRef:
    name: output-pipeline
  triggerRef:
    type: manual
  serviceAccount: 'default'
  results:
    type: 'gcs'
    url: 'gcs://somebucket/results/logs'
  resources:
  - name: first-create-file
    inputs:
    - name: workspace
      resourceRef:
        name: skaffold-git
    outputs:
    - name: workspace
      resourceRef:
        name: skaffold-git
  - name: then-check
    inputs:
    - name: workspace
      resourceRef:
        name: skaffold-git
