apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  name: pull-private-image-run
  labels:
    expect: succeeded
spec:
  serviceAccount: test-build-robot
  taskSpec:
    steps:
    - name: pull
      image: gcr.io/cloud-builders/docker
      args: ["pull", "gcr.io/build-crd-testing/secret-sauce"]
      volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
    volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
  trigger:
    type: manual
  results:
    type: 'gcs'
    url: 'gcs://somebucket/results/logs'
