apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-push-run
spec:
  taskRef:
    name: build-push
  trigger:
    type: manual
  results:
    type: 'gcs'
    url: 'gcs://somebucket/results/logs'
  inputs:
    resources:
    - name: workspace
      resourceRef:
        name: skaffold-git
    params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: /workspace/workspace/examples/microservices/leeroy-web
  outputs:
    resources:
    - name: builtImage
      resourceRef:
        name: skaffold-image-leeroy-web
